spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/toy_project?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  shutdown: graceful
  servlet:
    encoding:
      force-response: true

token:
  secretKey: "SpringBootJWTHelperTokenSecretKeyValue123!@#"
  accessTokenExpiryHours: 1
  refreshTokenExpiryHours: 12

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      reservationService:
        baseConfig: default
      redisService:
        baseConfig: default

